In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("movies_processed.csv")
print(data.shape)
data.head(20)

(2885, 6)

,year,title,length,score,sales,genre
0,1985,Witness,7,70,68,Crime
1,1985,The Last Dragon,15,64,25,Action
2,1985,Friday the 13th: A New Beginning,32,51,21,Horror
3,1985,Ladyhawke,9,68,18,Adventure
4,1985,Red Sonja,9,50,6,Adventure
5,1985,The Return of the Living Dead,29,73,14,Comedy
6,1985,Rambo: First Blood Part II,26,63,300,Action
7,1985,A View to a Kill,16,60,152,Adventure
8,1985,Return to Oz,12,67,11,Adventure
9,1985,Pale Rider,10,70,41,Romance
10,1985,Mad Max Beyond Thunderdome,26,59,36,Action
11,1985,Back to the Future,18,80,381,Adventure
12,1985,Day of the Dead,15,69,34,Horror
13,1985,My Beautiful Laundrette,23,66,2,Romance
14,1985,Commando,8,64,57,Action
15,1985,A Nightmare on Elm Street Part 2: Freddy's Rev...,50,57,29,Horror
16,1985,A Room with a View,18,69,20,Drama
17,1985,The Color Purple,16,77,146,Drama
18,1985,Out of Africa,13,70,128,Drama
19,1986,Invaders from Mars,18,55,4,Sci-Fi

In [3]:
data[["year", "length", "score", "sales"]] = data[["year", "length", "score", "sales"]].apply(pd.to_numeric)

In [4]:
score_arr = []
score = 0.0
while score < 10:
    score_arr.append(round(score,1))
    score += 0.1
score_arr = score_arr[:-1]

In [5]:
lst = []
yearDict = {}
for year in range(1985, 2017):
    scoreDict = { i : 0 for i in score_arr }
    for row in data[data['year'] == year].iterrows():
        avg = round(row[1]["score"] / 10, 1)
        scoreDict[avg] += 1
    #lst.append(list(scoreDict.values()))  
    yearDict[year] = list(scoreDict.values())
yearDict

{1985: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  2,
  0,
  1,
  1,
  1,
  2,
  3,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1986: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  3,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  2,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1987: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  3,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1988: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  2,
  0,
  1,
  0,
  2,
  1,
  1,
  0,
  0,
  0,
  2,
  0,
  0,
  2,
  2,
  0,
  1,
  3,
  2,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1989: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  3,
  0,
  0,
  2,
  1,
  0,
  1,
  3,
  0,
  2,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1990: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  3,
  0,
  0,
  3,
  2,
  0,
  0,
  2,
  0,
  0,
  1,
  1,
  4,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1991: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  3,
  3,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1992: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  0,
  0,
  2,
  0,
  1,
  0,
  1,
  1,
  3,
  2,
  1,
  3,
  1,
  0,
  2,
  0,
  3,
  2,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1993: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  2,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  2,
  1,
  0,
  0,
  0,
  3,
  0,
  1,
  1,
  0,
  2,
  1,
  1,
  2,
  2,
  1,
  2,
  0,
  3,
  3,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1994: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  3,
  0,
  0,
  1,
  2,
  2,
  0,
  1,
  2,
  6,
  2,
  2,
  0,
  2,
  0,
  1,
  0,
  2,
  2,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1995: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  2,
  0,
  3,
  0,
  4,
  3,
  2,
  1,
  0,
  2,
  3,
  1,
  1,
  3,
  1,
  5,
  2,
  3,
  3,
  2,
  2,
  2,
  1,
  3,
  0,
  0,
  0,
  3,
  1,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1996: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  2,
  3,
  1,
  1,
  2,
  8,
  2,
  2,
  0,
  2,
  2,
  3,
  3,
  4,
  1,
  6,
  3,
  5,
  5,
  0,
  0,
  2,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1997: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  2,
  0,
  0,
  1,
  0,
  1,
  3,
  1,
  1,
  1,
  1,
  2,
  4,
  2,
  3,
  3,
  3,
  2,
  5,
  2,
  5,
  5,
  3,
  2,
  2,
  3,
  3,
  2,
  4,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1998: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  5,
  3,
  1,
  2,
  4,
  6,
  4,
  3,
  7,
  3,
  5,
  1,
  4,
  7,
  4,
  1,
  3,
  4,
  1,
  1,
  2,
  2,
  0,
  2,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 1999: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  3,
  1,
  2,
  1,
  6,
  2,
  5,
  5,
  6,
  5,
  6,
  6,
  6,
  4,
  3,
  5,
  3,
  5,
  3,
  5,
  3,
  2,
  4,
  1,
  1,
  1,
  1,
  0,
  2,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2000: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  3,
  0,
  2,
  3,
  1,
  1,
  2,
  1,
  1,
  0,
  5,
  2,
  5,
  4,
  3,
  6,
  3,
  7,
  5,
  7,
  4,
  2,
  2,
  1,
  6,
  4,
  6,
  1,
  2,
  2,
  4,
  2,
  2,
  1,
  0,
  2,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2001: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  2,
  1,
  1,
  2,
  2,
  1,
  0,
  1,
  3,
  5,
  6,
  3,
  6,
  6,
  4,
  7,
  5,
  2,
  6,
  5,
  6,
  10,
  5,
  3,
  0,
  3,
  1,
  4,
  3,
  4,
  2,
  1,
  2,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2002: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  2,
  1,
  2,
  1,
  1,
  4,
  0,
  1,
  6,
  5,
  4,
  4,
  3,
  5,
  6,
  5,
  11,
  7,
  2,
  4,
  6,
  4,
  6,
  4,
  4,
  4,
  5,
  3,
  6,
  2,
  1,
  0,
  1,
  1,
  0,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2003: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  3,
  2,
  2,
  4,
  3,
  2,
  4,
  2,
  7,
  4,
  9,
  2,
  4,
  4,
  7,
  1,
  6,
  6,
  3,
  1,
  4,
  3,
  2,
  4,
  2,
  2,
  4,
  1,
  0,
  0,
  2,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2004: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  0,
  0,
  1,
  0,
  5,
  1,
  3,
  3,
  2,
  3,
  1,
  3,
  5,
  5,
  5,
  8,
  3,
  5,
  7,
  5,
  6,
  5,
  4,
  4,
  8,
  3,
  6,
  6,
  3,
  7,
  3,
  2,
  2,
  3,
  4,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2005: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  2,
  2,
  1,
  1,
  5,
  2,
  1,
  6,
  3,
  6,
  4,
  4,
  5,
  8,
  9,
  10,
  6,
  5,
  4,
  7,
  6,
  10,
  9,
  4,
  3,
  4,
  5,
  2,
  3,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2006: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  2,
  0,
  3,
  3,
  2,
  5,
  2,
  6,
  4,
  4,
  5,
  2,
  10,
  4,
  5,
  7,
  4,
  8,
  9,
  12,
  8,
  9,
  5,
  6,
  4,
  4,
  5,
  5,
  4,
  1,
  1,
  2,
  0,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2007: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  2,
  0,
  2,
  1,
  4,
  3,
  3,
  3,
  4,
  5,
  9,
  7,
  6,
  4,
  2,
  10,
  7,
  5,
  1,
  8,
  6,
  6,
  2,
  6,
  5,
  3,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2008: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  2,
  2,
  3,
  3,
  0,
  5,
  2,
  4,
  4,
  5,
  4,
  7,
  6,
  10,
  7,
  7,
  10,
  9,
  10,
  4,
  6,
  3,
  5,
  3,
  3,
  3,
  3,
  3,
  4,
  1,
  1,
  3,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2009: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  5,
  3,
  6,
  5,
  3,
  8,
  6,
  3,
  10,
  9,
  5,
  10,
  1,
  6,
  9,
  7,
  9,
  8,
  5,
  5,
  3,
  7,
  3,
  2,
  1,
  2,
  2,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2010: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  3,
  0,
  3,
  1,
  1,
  4,
  3,
  5,
  3,
  2,
  5,
  9,
  9,
  14,
  6,
  11,
  10,
  5,
  4,
  7,
  5,
  6,
  5,
  7,
  4,
  5,
  2,
  2,
  1,
  2,
  2,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2011: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  3,
  1,
  2,
  1,
  3,
  5,
  5,
  6,
  7,
  5,
  6,
  10,
  7,
  5,
  8,
  5,
  4,
  18,
  6,
  8,
  7,
  3,
  13,
  6,
  1,
  2,
  3,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2012: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  1,
  2,
  1,
  4,
  2,
  4,
  1,
  8,
  5,
  4,
  10,
  4,
  7,
  12,
  5,
  8,
  7,
  8,
  7,
  8,
  5,
  4,
  4,
  4,
  2,
  1,
  1,
  1,
  3,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2013: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  0,
  1,
  0,
  0,
  2,
  3,
  0,
  3,
  3,
  4,
  4,
  4,
  9,
  5,
  6,
  8,
  4,
  6,
  6,
  11,
  8,
  5,
  11,
  8,
  2,
  5,
  3,
  4,
  10,
  8,
  1,
  2,
  2,
  1,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2014: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  0,
  1,
  0,
  0,
  1,
  3,
  1,
  3,
  1,
  1,
  2,
  6,
  5,
  5,
  4,
  7,
  12,
  6,
  6,
  6,
  9,
  6,
  5,
  4,
  1,
  6,
  3,
  2,
  5,
  4,
  4,
  5,
  0,
  2,
  2,
  2,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2015: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  2,
  3,
  2,
  4,
  1,
  6,
  3,
  4,
  1,
  6,
  5,
  3,
  2,
  7,
  8,
  4,
  4,
  5,
  7,
  6,
  1,
  4,
  3,
  5,
  8,
  2,
  1,
  4,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 2016: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  3,
  1,
  4,
  4,
  6,
  3,
  6,
  5,
  2,
  4,
  5,
  3,
  4,
  4,
  5,
  1,
  0,
  2,
  3,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [6]:
scoreDf = pd.DataFrame()
for year in range(1985, 2017):
    #arrs = np.array_split(yearDict[year], 10)
    yearDf = pd.DataFrame(yearDict[year])

    yearDf['x'] = [0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,
                   0,1,2,3,4,5,6,7,8,9,]
    
    yearDf['y'] = [0,0,0,0,0,0,0,0,0,0,
                   1,1,1,1,1,1,1,1,1,1,
                   2,2,2,2,2,2,2,2,2,2,
                   3,3,3,3,3,3,3,3,3,3,
                   4,4,4,4,4,4,4,4,4,4,
                   5,5,5,5,5,5,5,5,5,5,
                   6,6,6,6,6,6,6,6,6,6,
                   7,7,7,7,7,7,7,7,7,7,
                   8,8,8,8,8,8,8,8,8,8,
                   9,9,9,9,9,9,9,9,9,9]
    yearDf['year'] = year
    scoreDf = pd.concat([scoreDf, yearDf])
scoreDf

    0  x  y  year
0   0  0  0  1985
1   0  1  0  1985
2   0  2  0  1985
3   0  3  0  1985
4   0  4  0  1985
5   0  5  0  1985
6   0  6  0  1985
7   0  7  0  1985
8   0  8  0  1985
9   0  9  0  1985
10  0  0  1  1985
11  0  1  1  1985
12  0  2  1  1985
13  0  3  1  1985
14  0  4  1  1985
15  0  5  1  1985
16  0  6  1  1985
17  0  7  1  1985
18  0  8  1  1985
19  0  9  1  1985
20  0  0  2  1985
21  0  1  2  1985
22  0  2  2  1985
23  0  3  2  1985
24  0  4  2  1985
25  0  5  2  1985
26  0  6  2  1985
27  0  7  2  1985
28  0  8  2  1985
29  0  9  2  1985
.. .. .. ..   ...
70  2  0  7  2016
71  3  1  7  2016
72  1  2  7  2016
73  1  3  7  2016
74  1  4  7  2016
75  0  5  7  2016
76  1  6  7  2016
77  0  7  7  2016
78  0  8  7  2016
79  0  9  7  2016
80  0  0  8  2016
81  0  1  8  2016
82  0  2  8  2016
83  0  3  8  2016
84  0  4  8  2016
85  0  5  8  2016
86  0  6  8  2016
87  0  7  8  2016
88  0  8  8  2016
89  0  9  8  2016
90  0  0  9  2016
91  0  1  9  2016
92  0  2  9  2016
93  0  3  9  2016
94  0  4  9  2016
95  0  5  9  2016
96  0  6  9  2016
97  0  7  9  2016
98  0  8  9  2016
99  0  9  9  2016

[3200 rows x 4 columns]

In [7]:
scoreDf.reset_index(inplace=True)
scoreDf.rename(columns={0: 'val'}, inplace=True)
scoreDf = scoreDf[['year', 'x', 'y', 'val']]
scoreDf

      year  x  y  val
0     1985  0  0    0
1     1985  1  0    0
2     1985  2  0    0
3     1985  3  0    0
4     1985  4  0    0
5     1985  5  0    0
6     1985  6  0    0
7     1985  7  0    0
8     1985  8  0    0
9     1985  9  0    0
10    1985  0  1    0
11    1985  1  1    0
12    1985  2  1    0
13    1985  3  1    0
14    1985  4  1    0
15    1985  5  1    0
16    1985  6  1    0
17    1985  7  1    0
18    1985  8  1    0
19    1985  9  1    0
20    1985  0  2    0
21    1985  1  2    0
22    1985  2  2    0
23    1985  3  2    0
24    1985  4  2    0
25    1985  5  2    0
26    1985  6  2    0
27    1985  7  2    0
28    1985  8  2    0
29    1985  9  2    0
...    ... .. ..  ...
3170  2016  0  7    2
3171  2016  1  7    3
3172  2016  2  7    1
3173  2016  3  7    1
3174  2016  4  7    1
3175  2016  5  7    0
3176  2016  6  7    1
3177  2016  7  7    0
3178  2016  8  7    0
3179  2016  9  7    0
3180  2016  0  8    0
3181  2016  1  8    0
3182  2016  2  8    0
3183  2016  3  8    0
3184  2016  4  8    0
3185  2016  5  8    0
3186  2016  6  8    0
3187  2016  7  8    0
3188  2016  8  8    0
3189  2016  9  8    0
3190  2016  0  9    0
3191  2016  1  9    0
3192  2016  2  9    0
3193  2016  3  9    0
3194  2016  4  9    0
3195  2016  5  9    0
3196  2016  6  9    0
3197  2016  7  9    0
3198  2016  8  9    0
3199  2016  9  9    0

[3200 rows x 4 columns]

In [17]:
games = pd.read_csv("game_scores_by_year.csv")
games.tail(25)

      year  x  y  val
3175  2016  5  7    4
3176  2016  6  7    2
3177  2016  7  7    1
3178  2016  8  7    3
3179  2016  9  7    2
3180  2016  0  8    0
3181  2016  1  8    4
3182  2016  2  8    3
3183  2016  3  8    1
3184  2016  4  8    2
3185  2016  5  8    1
3186  2016  6  8    3
3187  2016  7  8    1
3188  2016  8  8    0
3189  2016  9  8    1
3190  2016  0  9    0
3191  2016  1  9    0
3192  2016  2  9    0
3193  2016  3  9    0
3194  2016  4  9    0
3195  2016  5  9    0
3196  2016  6  9    0
3197  2016  7  9    0
3198  2016  8  9    0
3199  2016  9  9    0

In [16]:
scoreDf.tail(25)

      year  x  y  val
3175  2016  5  7    0
3176  2016  6  7    1
3177  2016  7  7    0
3178  2016  8  7    0
3179  2016  9  7    0
3180  2016  0  8    0
3181  2016  1  8    0
3182  2016  2  8    0
3183  2016  3  8    0
3184  2016  4  8    0
3185  2016  5  8    0
3186  2016  6  8    0
3187  2016  7  8    0
3188  2016  8  8    0
3189  2016  9  8    0
3190  2016  0  9    0
3191  2016  1  9    0
3192  2016  2  9    0
3193  2016  3  9    0
3194  2016  4  9    0
3195  2016  5  9    0
3196  2016  6  9    0
3197  2016  7  9    0
3198  2016  8  9    0
3199  2016  9  9    0

In [18]:
scoreDf["val"] = scoreDf["val"] + games["val"]

c:\users\lynko\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [19]:
scoreDf.tail(25)

      year  x  y  val
3175  2016  5  7    4
3176  2016  6  7    3
3177  2016  7  7    1
3178  2016  8  7    3
3179  2016  9  7    2
3180  2016  0  8    0
3181  2016  1  8    4
3182  2016  2  8    3
3183  2016  3  8    1
3184  2016  4  8    2
3185  2016  5  8    1
3186  2016  6  8    3
3187  2016  7  8    1
3188  2016  8  8    0
3189  2016  9  8    1
3190  2016  0  9    0
3191  2016  1  9    0
3192  2016  2  9    0
3193  2016  3  9    0
3194  2016  4  9    0
3195  2016  5  9    0
3196  2016  6  9    0
3197  2016  7  9    0
3198  2016  8  9    0
3199  2016  9  9    0

In [20]:
scoreDf.to_csv("gm_scores_by_year.csv", index=False)