In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("games.csv")
data.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,User_Score,Rating,Score_Diff
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,80.0,E,-4.0
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,83.0,E,-1.0
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,80.0,E,0.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN

In [3]:
data["Year"].unique()

array([2006., 1985., 2008., 2009., 1996., 1989., 1984., 2005., 1999.,
       2007., 2010., 2013., 2004., 1990., 1988., 2002., 2001., 2011.,
       1998., 2015., 2012., 2014., 1992., 1997., 1993., 1994., 1982.,
       2016., 2003., 1986., 2000., 1995., 1991., 1981., 1987., 1980.,
       1983., 1978.])

In [4]:
data["Genre"].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

In [5]:
down85 = data[(data['Year'] > 1975) & (data['Year'] <= 1985)]
down95 = data[(data['Year'] > 1985) & (data['Year'] <= 1995)]
down05 = data[(data['Year'] > 1995) & (data['Year'] <= 2005)]
down16 = data[(data['Year'] > 2005) & (data['Year'] <= 2016)]

In [6]:
down85

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,User_Score,Rating,Score_Diff
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN
9,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31,NaN,NaN,NaN,NaN
89,Pac-Man,2600,1982.0,Puzzle,Atari,7.28,0.45,0.00,0.08,7.81,NaN,NaN,NaN,NaN
240,Pitfall!,2600,1981.0,Platform,Activision,4.21,0.24,0.00,0.05,4.50,NaN,NaN,NaN,NaN
262,Asteroids,2600,1980.0,Shooter,Atari,4.00,0.26,0.00,0.05,4.31,NaN,NaN,NaN,NaN
281,Excitebike,NES,1984.0,Racing,Nintendo,2.04,0.48,1.57,0.07,4.16,NaN,NaN,NaN,NaN
300,Golf,NES,1984.0,Sports,Nintendo,1.22,0.28,2.46,0.04,4.01,NaN,NaN,NaN,NaN
374,Kung Fu,NES,1985.0,Action,Nintendo,1.64,0.38,1.42,0.06,3.50,NaN,NaN,NaN,NaN
426,Baseball,NES,1983.0,Sports,Nintendo,0.73,0.10,2.35,0.02,3.20,NaN,NaN,NaN,NaN
546,Missile Command,2600,1980.0,Shooter,Atari,2.56,0.17,0.00,0.03,2.76,NaN,NaN,NaN,NaN
609,Space Invaders,2600,1978.0,Shooter,Atari,2.36,0.14,0.00,0.03,2.53,NaN,NaN,NaN,NaN
698,Mario Bros.,NES,1983.0,Platform,Nintendo,0.51,0.12,1.63,0.02,2.28,NaN,NaN,NaN,NaN
736,Frogger,2600,1981.0,Action,Parker Bros.,2.06,0.12,0.00,0.02,2.20,NaN,NaN,NaN,NaN
757,Tennis,NES,1984.0,Sports,Nintendo,0.48,0.11,1.56,0.02,2.17,NaN,NaN,NaN,NaN
772,Mahjong,NES,1983.0,Misc,Nintendo,0.01,0.00,2.13,0.00,2.14,NaN,NaN,NaN,NaN
773,Demon Attack,2600,1981.0,Shooter,Imagic,1.99,0.12,0.00,0.02,2.13,NaN,NaN,NaN,NaN
866,E.T.: The Extra Terrestrial,2600,1981.0,Action,Atari,1.84,0.11,0.00,0.02,1.97,NaN,NaN,NaN,NaN
869,Soccer,NES,1985.0,Sports,Nintendo,0.18,0.23,1.53,0.02,1.96,NaN,NaN,NaN,NaN
942,Pinball,NES,1984.0,Action,Nintendo,0.80,0.19,0.83,0.03,1.85,NaN,NaN,NaN,NaN
1108,Ms. Pac-Man,2600,1981.0,Puzzle,Atari,1.54,0.10,0.00,0.02,1.65,NaN,NaN,NaN,NaN
1119,Dig Dug,2600,1982.0,Puzzle,Atari,1.52,0.10,0.00,0.02,1.64,NaN,NaN,NaN,NaN
1154,River Raid,2600,1981.0,Shooter,Activision,1.49,0.09,0.00,0.02,1.60,NaN,NaN,NaN,NaN
1164,Mario Bros.,2600,1982.0,Platform,Atari,1.48,0.09,0.00,0.02,1.59,NaN,NaN,NaN,NaN
1233,Xevious,NES,1984.0,Shooter,Namco Bandai Games,0.18,0.06,1.27,0.01,1.52,NaN,NaN,NaN,NaN
1234,F1 Race,NES,1984.0,Racing,Nintendo,0.00,0.00,1.52,0.00,1.52,NaN,NaN,NaN,NaN
1262,Ice Climber,NES,1985.0,Platform,Nintendo,0.46,0.10,0.92,0.02,1.50,NaN,NaN,NaN,NaN
1305,Donkey Kong,2600,1981.0,Platform,Coleco,1.36,0.08,0.00,0.02,1.46,NaN,NaN,NaN,NaN
1318,4 Nin uchi Mahjong,NES,1984.0,Misc,Nintendo,0.00,0.00,1.45,0.00,1.45,NaN,NaN,NaN,NaN
1426,Centipede,2600,1981.0,Shooter,Atari,1.26,0.08,0.00,0.01,1.36,NaN,NaN,NaN,NaN
1482,Gyromite,NES,1985.0,Puzzle,Nintendo,0.73,0.16,0.40,0.03,1.32,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3174,X-Man,2600,1982.0,Action,Universal Gamex,0.58,0.04,0.00,0.01,0.63,NaN,NaN,NaN,NaN
3203,Battlezone,2600,1982.0,Shooter,Atari,0.58,0.03,0.00,0.01,0.62,NaN,NaN,NaN,NaN
3217,Halloween,2600,1982.0,Action,Wizard Video Games,0.58,0.03,0.00,0.01,0.62,NaN,NaN,NaN,NaN
3363,BurgerTime,2600,1981.0,Puzzle,Mattel Interactive,0.55,0.03,0.00,0.01,0.59,NaN,NaN,NaN,NaN
3367,Smurf: Rescue In Gargamel's Castle,2600,1981.0,Action,Coleco,0.55,0.03,0.00,0.01,0.59,NaN,NaN,NaN,NaN
3401,Q*bert,2600,1982.0,Puzzle,Parker Bros.,0.55,0.03,0.00,0.01,0.58,NaN,NaN,NaN,NaN
3597,The Activision Decathlon,2600,1982.0,Sports,Activision,0.52,0.03,0.00,0.01,0.55,NaN,NaN,NaN,NaN
3670,Action Force,2600,1982.0,Action,CPG Products,0.50,0.03,0.00,0.01,0.54,NaN,NaN,NaN,NaN
3699,Popeye,2600,1982.0,Platform,Parker Bros.,0.50,0.03,0.00,0.01,0.54,NaN,NaN,NaN,NaN
3867,Wrecking Crew,NES,1985.0,Platform,Nintendo,0.00,0.00,0.51,0.00,0.51,NaN,NaN,NaN,NaN
3904,Midnight Magic,2600,1983.0,Action,Atari,0.47,0.03,0.00,0.01,0.50,NaN,NaN,NaN,NaN
3919,Chopper Command,2600,1982.0,Shooter,Activision,0.47,0.03,0.00,0.01,0.50,NaN,NaN,NaN,NaN
3963,RealSports Tennis,2600,1982.0,Sports,Atari,0.46,0.03,0.00,0.01,0.50,NaN,NaN,NaN,NaN
3965,Raiders of the Lost Ark,2600,1981.0,Action,Atari,0.46,0.03,0.00,0.01,0.50,NaN,NaN,NaN,NaN
3966,Gauntlet,2600,1982.0,Action,Answer Software,0.46,0.03,0.00,0.01,0.50,NaN,NaN,NaN,NaN
3981,Ice Hockey,2600,1980.0,Sports,Activision,0.46,0.03,0.00,0.01,0.49,NaN,NaN,NaN,NaN
4041,Millipede,2600,1983.0,Shooter,Atari,0.45,0.03,0.00,0.01,0.48,NaN,NaN,NaN,NaN
4085,Grand Prix,2600,1981.0,Racing,Activision,0.45,0.03,0.00,0.00,0.48,NaN,NaN,NaN,NaN
4203,Gremlins,2600,1983.0,Action,Atari,0.43,0.03,0.00,0.00,0.46,NaN,NaN,NaN,NaN
4253,Ghostbusters,2600,1985.0,Puzzle,Activision,0.42,0.03,0.00,0.00,0.45,NaN,NaN,NaN,NaN
4266,Phoenix,2600,1981.0,Simulation,Atari,0.42,0.02,0.00,0.00,0.45,NaN,NaN,NaN,NaN
4322,Jawbreaker,2600,1981.0,Action,Tigervision,0.42,0.03,0.00,0.00,0.45,NaN,NaN,NaN,NaN
4452,Barnstorming,2600,1981.0,Action,Activision,0.40,0.02,0.00,0.00,0.43,NaN,NaN,NaN,NaN
4660,Dig Dug,NES,1985.0,Puzzle,Namco Bandai Games,0.00,0.00,0.41,0.00,0.41,NaN,NaN,NaN,NaN
4709,Pengo,2600,1983.0,Adventure,Atari,0.38,0.02,0.00,0.00,0.40,NaN,NaN,NaN,NaN
4712,Mouse Trap,2600,1981.0,Action,Coleco,0.38,0.02,0.00,0.00,0.40,NaN,NaN,NaN,NaN
4728,Congo Bongo,2600,1982.0,Action,Sega,0.37,0.02,0.00,0.00,0.40,NaN,NaN,NaN,NaN
4820,Bump 'n' Jump,2600,1982.0,Racing,Mattel Interactive,0.37,0.02,0.00,0.00,0.39,NaN,NaN,NaN,NaN
4840,Laser Blast,2600,1981.0,Action,Activision,0.37,0.02,0.00,0.00,0.39,NaN,NaN,NaN,NaN
4895,Airlock,2600,1981.0,Action,Data Age,0.36,0.02,0.00,0.00,0.39,NaN,NaN,NaN,NaN

In [7]:
def process_publishers(df):
    res = []
    for index, value in df["Publisher"].value_counts().iteritems():
        if len(res) < 6:
            res.append(index)
            res.append(value)
    return res

In [8]:
def process_genres(df):
    res = []
    for index, value in df["Genre"].value_counts().iteritems():
        res.append(index)
        res.append(value)
    for genre in data["Genre"].unique():
        if genre not in res:
            res.append(genre)
            res.append(0)
    return res

In [9]:
def process_platforms(df):
    return df["Platform"].mode()[0]

In [10]:
def process_names(df):
    arr = []
    for name in df["Name"]:
        arr.append(len(name))
    return round(np.array(arr).mean(), 3)

In [11]:
def process_sales(df):
    arr = []
    arr.append(round(df["NA_Sales"].sum(), 2))
    arr.append(round(df["EU_Sales"].sum(), 2))
    arr.append(round(df["JP_Sales"].sum(), 2))
    arr.append(round(df["Other_Sales"].sum(), 2))    
    arr.append(round(df["Global_Sales"].sum(), 2))   
    return arr

In [12]:
def process_games(df):
    return df.shape[0]

In [13]:
def process_year(df, decade):
    names = process_names(df)
    games = process_games(df)
    #platform = process_platforms(df)
    genres = process_genres(df)
    sales = process_sales(df)
    #publishers = process_publishers(df)
    
    colGenres = ["Genre1","Genre1Count","Genre2","Genre2Count","Genre3","Genre3Count",
                 "Genre4","Genre4Count","Genre5","Genre5Count","Genre6","Genre6Count",
                 "Genre7","Genre7Count","Genre8","Genre8Count","Genre9","Genre9Count",
                 "Genre10","Genre10Count","Genre11","Genre11Count","Genre12","Genre12Count"
                ]
    
    colSales = ["NA_Sales","EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]
    
    #colPublishers = ["Publisher1","Publisher1Count","Publisher2","Publisher2Count","Publisher3","Publisher3Count"]
    
    first = [year, names, games]#, platform]
    #dfFirst = pd.DataFrame([first], columns=["Decade", "Average Title Length", "Games", "Top Platform"])
    dfFirst = pd.DataFrame([first], columns=["Year", "Average Title Length", "Games"])
    dfGenres = pd.DataFrame([genres], columns=colGenres)
    dfSales = pd.DataFrame([sales], columns=colSales)
    #dfPublishers = pd.DataFrame([publishers], columns=colPublishers)
    
    #result = pd.concat([dfFirst, dfGenres, dfSales, dfPublishers], axis=1)
    result = pd.concat([dfFirst, dfGenres, dfSales], axis=1)
    return result

In [14]:
#dfs = [down85, down95, down05, down16]
#decades = ["1975-1985", "1986-1995", "1996-2005", "2006-2016"]
arr = []
#for i in range(len(dfs)):
for year in range(1985, 2017):
    arr.append(
        #process_year(dfs[i], decades[i])
        process_year(data[data['Year'] == year], year)
    )
df = pd.concat(arr)
df.head(35)

,Year,Average Title Length,Games,Genre1,Genre1Count,Genre2,Genre2Count,Genre3,Genre3Count,Genre4,...,Genre10Count,Genre11,Genre11Count,Genre12,Genre12Count,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1985,11.167,12,Platform,4,Puzzle,4,Action,1,Fighting,...,0,Adventure,0,Strategy,0,33.73,4.71,14.54,0.91,53.89
0,1986,17.947,19,Platform,6,Action,6,Shooter,3,Sports,...,0,Adventure,0,Strategy,0,11.87,2.80,19.81,1.93,36.41
0,1987,19.385,13,Role-Playing,3,Platform,2,Action,2,Sports,...,0,Simulation,0,Strategy,0,8.08,1.40,11.63,0.20,21.33
0,1988,16.769,13,Platform,4,Role-Playing,3,Sports,2,Action,...,0,Adventure,0,Strategy,0,23.65,6.56,15.76,0.98,46.95
0,1989,14.600,15,Platform,3,Puzzle,3,Sports,3,Action,...,0,Adventure,0,Strategy,0,44.95,8.43,18.36,1.50,73.24
0,1990,16.143,14,Platform,3,Action,3,Role-Playing,2,Puzzle,...,0,Adventure,0,Strategy,0,25.46,7.63,14.25,1.40,48.76
0,1991,19.900,20,Platform,4,Action,3,Puzzle,3,Adventure,...,1,Misc,0,Strategy,0,12.76,3.95,10.28,0.74,27.73
0,1992,20.962,26,Fighting,5,Platform,4,Role-Playing,4,Puzzle,...,1,Shooter,0,Strategy,0,33.81,11.65,26.72,1.64,73.82
0,1993,17.828,29,Platform,8,Fighting,7,Role-Playing,4,Sports,...,0,Simulation,0,Adventure,0,16.61,5.07,21.05,0.96,43.68
0,1994,18.326,43,Sports,9,Platform,8,Fighting,6,Shooter,...,2,Action,1,Misc,1,27.80,14.65,22.59,2.08,67.07
0,1995,19.577,52,Role-Playing,12,Fighting,8,Sports,6,Platform,...,2,Shooter,1,Adventure,0,21.57,12.75,29.97,2.03,66.32
0,1996,18.311,90,Sports,16,Racing,13,Role-Playing,11,Fighting,...,5,Strategy,4,Puzzle,2,80.52,43.28,43.05,6.70,173.48
0,1997,18.416,113,Sports,25,Racing,15,Action,12,Role-Playing,...,4,Misc,4,Adventure,2,85.58,43.35,35.12,7.82,171.76
0,1998,19.204,152,Sports,41,Racing,19,Action,16,Fighting,...,5,Puzzle,4,Adventure,4,115.82,60.30,39.81,9.58,225.61
0,1999,20.155,148,Sports,24,Action,21,Racing,21,Role-Playing,...,7,Adventure,6,Puzzle,1,111.43,56.35,43.60,8.93,220.45
0,2000,20.566,129,Sports,29,Action,19,Racing,16,Role-Playing,...,4,Adventure,3,Simulation,2,79.40,43.92,33.45,9.53,166.23
0,2001,21.827,185,Sports,36,Action,28,Racing,25,Platform,...,7,Strategy,6,Puzzle,4,154.79,83.12,32.56,19.98,290.35
0,2002,23.918,233,Sports,42,Action,41,Shooter,34,Platform,...,5,Adventure,5,Puzzle,3,171.33,90.82,32.31,23.72,318.18
0,2003,24.829,246,Action,48,Sports,46,Platform,27,Racing,...,6,Puzzle,2,Adventure,1,155.94,87.49,27.22,23.41,293.94
0,2004,24.542,271,Sports,48,Action,46,Platform,32,Shooter,...,7,Puzzle,7,Strategy,6,184.89,90.33,35.29,43.53,354.01
0,2005,25.449,267,Action,58,Sports,42,Shooter,34,Racing,...,6,Puzzle,5,Strategy,4,187.27,103.33,46.11,35.77,372.59
0,2006,23.781,228,Action,42,Sports,41,Racing,27,Shooter,...,7,Puzzle,5,Strategy,2,217.29,118.90,53.05,49.09,438.33
0,2007,23.566,366,Action,78,Sports,52,Misc,49,Shooter,...,11,Fighting,11,Strategy,9,258.29,147.89,39.38,70.60,516.06
0,2008,22.551,425,Action,91,Sports,67,Misc,62,Simulation,...,13,Strategy,11,Puzzle,9,279.23,167.88,40.03,71.86,558.92
0,2009,23.217,373,Action,87,Misc,58,Sports,57,Shooter,...,13,Platform,11,Strategy,8,260.99,161.23,44.99,60.96,528.02
0,2010,21.609,322,Action,77,Sports,58,Misc,43,Role-Playing,...,7,Puzzle,6,Strategy,4,243.85,148.13,40.33,49.62,482.01
0,2011,20.859,269,Action,62,Shooter,45,Sports,32,Misc,...,6,Adventure,6,Puzzle,2,192.71,136.92,30.39,43.83,403.96
0,2012,21.351,208,Action,85,Shooter,27,Role-Playing,25,Sports,...,4,Strategy,3,Puzzle,2,137.50,102.26,33.57,32.67,305.89
0,2013,19.143,182,Action,54,Shooter,27,Sports,26,Role-Playing,...,3,Simulation,3,Puzzle,1,141.31,110.28,32.50,35.03,319.05
0,2014,19.179,184,Action,59,Shooter,34,Sports,32,Role-Playing,...,1,Puzzle,1,Strategy,0,119.13,109.93,25.68,33.17,287.85
0,2015,20.276,145,Action,47,Sports,23,Shooter,22,Role-Playing,...,1,Simulation,1,Strategy,1,94.29,83.67,21.02,26.89,225.92
0,2016,18.485,68,Shooter,19,Action,18,Sports,11,Role-Playing,...,1,Puzzle,0,Strategy,0,35.15,38.85,8.39,11.52,93.87

In [15]:
cols = ["Year","Games","NA_Sales","EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]
sales = df[cols]

   Year  Games  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0  1985     12     33.73      4.71     14.54         0.91         53.89
0  1986     19     11.87      2.80     19.81         1.93         36.41
0  1987     13      8.08      1.40     11.63         0.20         21.33
0  1988     13     23.65      6.56     15.76         0.98         46.95
0  1989     15     44.95      8.43     18.36         1.50         73.24
0  1990     14     25.46      7.63     14.25         1.40         48.76
0  1991     20     12.76      3.95     10.28         0.74         27.73
0  1992     26     33.81     11.65     26.72         1.64         73.82
0  1993     29     16.61      5.07     21.05         0.96         43.68
0  1994     43     27.80     14.65     22.59         2.08         67.07
0  1995     52     21.57     12.75     29.97         2.03         66.32
0  1996     90     80.52     43.28     43.05         6.70        173.48
0  1997    113     85.58     43.35     35.12         7.82        171.76
0  1998    152    115.82     60.30     39.81         9.58        225.61
0  1999    148    111.43     56.35     43.60         8.93        220.45
0  2000    129     79.40     43.92     33.45         9.53        166.23
0  2001    185    154.79     83.12     32.56        19.98        290.35
0  2002    233    171.33     90.82     32.31        23.72        318.18
0  2003    246    155.94     87.49     27.22        23.41        293.94
0  2004    271    184.89     90.33     35.29        43.53        354.01
0  2005    267    187.27    103.33     46.11        35.77        372.59
0  2006    228    217.29    118.90     53.05        49.09        438.33
0  2007    366    258.29    147.89     39.38        70.60        516.06
0  2008    425    279.23    167.88     40.03        71.86        558.92
0  2009    373    260.99    161.23     44.99        60.96        528.02
0  2010    322    243.85    148.13     40.33        49.62        482.01
0  2011    269    192.71    136.92     30.39        43.83        403.96
0  2012    208    137.50    102.26     33.57        32.67        305.89
0  2013    182    141.31    110.28     32.50        35.03        319.05
0  2014    184    119.13    109.93     25.68        33.17        287.85
0  2015    145     94.29     83.67     21.02        26.89        225.92
0  2016     68     35.15     38.85      8.39        11.52         93.87

In [17]:
#df.to_csv("sales_by_year.csv", index=False)